### ISSUE TITLE
Pin1 of the ATmega32U4 is incorrectly connected to pin33

### ISSUE THREAD

**Issue by dcelectr** [eltorio/leonardo#1]
During the import the diagonal line of net D7 was close to RN1C
![Error](https://user-images.githubusercontent.com/48794887/221466372-74693f61-d3f8-4319-91e7-3f7fc5c1af70.jpg)
See how it is in the PDF
![correct](https://user-images.githubusercontent.com/48794887/221466382-738b46df-8fe1-4ff6-a336-09e7574ddfcc.jpg)
Also in the Eagle layout the Pin 33  ATmega32U4 goes only to RN1C
![Layout](https://user-images.githubusercontent.com/48794887/221466385-97115688-a88b-4dce-98a9-ff4bd2655d01.jpg)

**Comment by eltorio** [comment]
Thanks,
Corrected in e10cf282fa710b1ea3066e1623296bcfc7b7702d
